---
include:
  # Scanner mode (non-touch by default)
  # For touch mode: Edit config/prospector_scanner.conf
  - board: xiao_ble
    shield: prospector_scanner

  # Settings reset utility
  - board: xiao_ble
    shield: settings_reset
